/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"


void
rand_prog_1(char *host, long semilla, int iter)
{
	CLIENT *clnt;
	void  *result_1;
	long  inicializa_random_1_arg;
	long  *result_2;
	char *obtiene_siguiente_random_1_arg;
	int i;
	inicializa_random_1_arg = semilla;

#ifndef	DEBUG
	clnt = clnt_create (host, RAND_PROG, RAND_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = inicializa_random_1(&inicializa_random_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Inizializado de forma exitosa\n");
	}
	for (i = 0; i < iter; i++){
	result_2 = obtiene_siguiente_random_1((void*)&obtiene_siguiente_random_1_arg, clnt);
	if (result_2 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
			printf("%d : %d\n", i, (int)*result_2);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int semilla, iteraciones;

	if (argc < 4) {
		printf ("Uso: %s semilla iteraciones\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	semilla= atoi(argv[2]);
	iteraciones= atoi(argv[3]);
	rand_prog_1 (host, semilla, iteraciones);
exit (0);
}
