/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"

void *
inicializa_random_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	 printf("Se llamó a inicializar_random_1_svc\n");
	srandom(*argp);
	
	return (void *) &result;
}

long *
obtiene_siguiente_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static long  result;

	/*
	 * insert server code here
	 */
	result = random();
	printf("se llamó a obtiene_siguiente_random_1_svc\n");
	printf("generado %d\n",(int)result);

	return &result;
}


