/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numeros {
	int a;
	int b;
};
typedef struct numeros numeros;

#define CALCULADORA 0x31111111
#define OPERACIONES 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  int * suma_1(numeros *, CLIENT *);
extern  int * suma_1_svc(numeros *, struct svc_req *);
#define RESTA 2
extern  int * resta_1(numeros *, CLIENT *);
extern  int * resta_1_svc(numeros *, struct svc_req *);
#define MULTIPLICACION 3
extern  int * multiplicacion_1(numeros *, CLIENT *);
extern  int * multiplicacion_1_svc(numeros *, struct svc_req *);
#define DIVICION 4
extern  int * divicion_1(numeros *, CLIENT *);
extern  int * divicion_1_svc(numeros *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define RESTA 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define MULTIPLICACION 3
extern  int * multiplicacion_1();
extern  int * multiplicacion_1_svc();
#define DIVICION 4
extern  int * divicion_1();
extern  int * divicion_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numeros (XDR *, numeros*);

#else /* K&R C */
extern bool_t xdr_numeros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
