/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calculadora_1(char *host, char *operacion, int num1, int num2)
{
	CLIENT *clnt;
	int  *result_1;
	numeros  suma_1_arg;
	int  *result_2;
	numeros  resta_1_arg;
	int  *result_3;
	numeros  multiplicacion_1_arg;
	int  *result_4;
	numeros  divicion_1_arg;
	suma_1_arg.a=num1;
	suma_1_arg.b=num2;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, OPERACIONES, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */


	switch (*operacion)
	{
	case 's':
		result_1 = suma_1(&suma_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf("Resultado: %d\n", *result_1);
		}

		break;
	case 'r':
		result_2 = resta_1(&suma_1_arg, clnt);
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf("Resultado: %d\n", *result_2);
		}

		break;
	case 'm':
		result_3 = multiplicacion_1(&suma_1_arg, clnt);
		if (result_3 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf("Resultado: %d\n", *result_3);
		}

		break;
	case 'd':
		result_4 = divicion_1(&suma_1_arg, clnt);
		if (result_4 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf("Resultado: %d\n", *result_4);
		}

		break;
	default:
		printf("Algo salio mal D:");
		break;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *operacion; int num1, num2;

	if (argc < 5) {
		printf ("Usa: %s server_host operacion(s->para suma,r->para resta,d->para divicion,m->para multiplicacion) numero1 numero2\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	operacion = argv[2];
	num1 = atoi(argv[3]);
	num2 = atoi(argv[4]);
	
	calculadora_1 (host, operacion, num1, num2);
exit (0);
}
